name: Product Service CI

on:
  push:
    branches: [ "main", "Setup-CI-using-GitHub-Action-infra" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/workflows/actions
      - name: Run Maven Build Command
        run: mvn clean install -DskipTests

  Unit-Tests:
    needs: Build
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/workflows/actions
      - name: Run Maven Test
        run: mvn test
      - name: Unit Test Results
        uses: dorny/test-reporter@v1
        if: always()
        with:
          name: Unit-Test-Results
          path: "**/surefire-reports/*.xml"
          reporter: java-junit
