version: "3.9"

services:
  search:
    image: ghcr.io/nashtech-garage/yas-search:latest
    entrypoint: [ "./wait-for-it.sh", "elasticsearch:9200", "--timeout=300", "--", "java", "-jar", "/search-0.0.1-SNAPSHOT.jar" ]
    environment:
      SERVER_SERVLET_CONTEXT_PATH: /search
      YAS_PUBLIC_URL: http://api.yas.local/search
      YAS_SERVICES_PRODUCT: http://product/product
      SERVER_PORT: "80"
    networks:
      - yas-network
  elasticsearch:
    image: elasticsearch:8.6.2
    volumes:
      - esdata:/usr/share/elasticsearch/data
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - xpack.security.enabled=false
      - "discovery.type=single-node"
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      - yas-network

networks:
  yas-network:

volumes:
  esdata: