version: "3.8"
services:
  nginx:
    image: nginx
    volumes:
      - ./nginx/templates:/etc/nginx/templates
    ports:
      - "80:80"
  keycloak:
    image: quay.io/keycloak/keycloak:16.1.0
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
      PROXY_ADDRESS_FORWARDING: "true"
      DB_VENDOR: POSTGRES
      DB_USER: admin
      DB_PASSWORD: admin
      DB_ADDR: postgres
      DB_DATABASE: keycloak
  media:
    image: ghcr.io/nashtech-garage/yas-media:latest
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/media
      SERVER_SERVLET_CONTEXT_PATH: /media
      YAS_PUBLICURL: http://api.yas.local/media
      SERVER_PORT: "80"
      SPRING_SLEUTH_OTEL_EXPORTER_OTLP_ENDPOINT: http://jaeger:4317
  postgres:
    image: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
  pgadmin:
    image: dpage/pgadmin4
    volumes:
      - pgadmin:/var/lib/pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@yas.com
      PGADMIN_DEFAULT_PASSWORD: admin
  jaeger:
    image: jaegertracing/all-in-one:1.36
    environment:
      COLLECTOR_OTLP_ENABLED: "true"
volumes:
  postgres:
  pgadmin:
