apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "eventuate-cdc.fullname" . }}
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "eventuate-cdc.fullname" . }}
  endpoints:
    - port: 'http'
      path: '/actuator/prometheus'