domain: yas.local.com
postgresql:
  replicas: 1
  username: yasadminuser
  password: admin
kafka:
  replicas: 1
zookeeper:
  replicas: 1
elasticsearch:
  replicas: 1
  username: yas
  password: LarUmB3A49NTg9YmgW4=
keycloakRealm:
  backofficeUrl: http://backoffice.yas.local.com
  storefrontUrl: http://storefront.yas.local.com