apiVersion: k8s.keycloak.org/v2alpha1
kind: Keycloak
metadata:
  name: keycloak
spec:
  db:
    vendor: postgres
    usernameSecret:
      name: postgresql-credentials
      key: username
    passwordSecret:
      name: postgresql-credentials
      key: password
    host: postgresql.postgres
    database: keycloak
    port: 5432
  http:
    httpEnabled: true
    httpPort: 8180
  hostname:
    hostname: {{ .Values.hostname }}
    strict: false
    strictBackchannel: false
  unsupported:
    podTemplate:
      spec:
        volumes:
          - name: yas-themes
            configMap:
              name: yas-themes-configmap
        containers:
          - name: keycloak
            env:
              - name: KC_HOSTNAME_STRICT_HTTPS
                value: "false"
            volumeMounts:
              - name: yas-themes
                mountPath: /opt/keycloak/providers
