backend:
  image:
    repository: ghcr.io/nashtech-garage/yas-order
    tag: latest

  nameOverride: order
  fullnameOverride: order
  databaseName: order
  ingress:
    enabled: true
    host: api.yas.local.com
    path: /order
