apiVersion: v1
kind: Secret
metadata:
  name: eventuate-cdc-env-secret
  annotations:
    reloader.stakater.com/match: "true"
type: Opaque
stringData:
  CDC_OPTS: "--debug"
  EVENTUATELOCAL_KAFKA_BOOTSTRAP_SERVERS: "kafka-cluster-kafka-brokers.kafka:9092"
  EVENTUATELOCAL_ZOOKEEPER_CONNECTION_STRING: "zookeeper.zookeeper:2181"
  {{- range $index, $config := .Values.eventuateCdcConfig }}
  EVENTUATE_CDC_READER_READER{{ $index }}_TYPE: "postgres-wal"
  EVENTUATE_CDC_READER_READER{{ $index }}_DATASOURCEURL: "jdbc:postgresql://postgresql.postgres/{{ $config.database }}"
  EVENTUATE_CDC_READER_READER{{ $index }}_MONITORINGSCHEMA: "eventuate"
  EVENTUATE_CDC_READER_READER{{ $index }}_DATASOURCEUSERNAME: "{{ $.Values.credentials.postgresql.username }}"
  EVENTUATE_CDC_READER_READER{{ $index }}_DATASOURCEPASSWORD: "{{ $.Values.credentials.postgresql.password }}"
  EVENTUATE_CDC_READER_READER{{ $index }}_DATASOURCEDRIVERCLASSNAME: "org.postgresql.Driver"
  EVENTUATE_CDC_READER_READER{{ $index }}_LEADERSHIPLOCKPATH: "/eventuate/cdc/leader/eventuate/{{ $config.database }}"
  EVENTUATE_CDC_READER_READER{{ $index }}_OFFSETSTORAGETOPICNAME: "db.history.common"
  EVENTUATE_CDC_READER_READER{{ $index }}_OUTBOXID: "{{ $index }}"
  EVENTUATE_CDC_READER_READER{{ $index }}_POSTGRESREPLICATIONSLOTNAME: "eventuate_slot_{{ $config.database }}"
  EVENTUATE_CDC_PIPELINE_PIPELINE{{ $index }}_TYPE: "eventuate-tram"
  EVENTUATE_CDC_PIPELINE_PIPELINE{{ $index }}_READER: "reader{{ $index }}"
  EVENTUATE_CDC_PIPELINE_PIPELINE{{ $index }}_EVENTUATEDATABASESCHEMA: "eventuate"
  {{- end }}