backend:
  image:
    repository: ghcr.io/nashtech-garage/yas-payment
    tag: latest

  nameOverride: payment
  fullnameOverride: payment
  databaseName: payment
  ingress:
    enabled: true
    host: api.yas.local.com
    path: /payment
  extraVolumes:
    - name: payment-application-config
      configMap:
        name: payment-application-configmap
  extraVolumeMounts:
    - name: payment-application-config
      mountPath: /opt/yas/payment
  extraApplicationConfigPaths:
    - /opt/yas/payment/payment-application.yaml