backend:
  image:
    repository: ghcr.io/nashtech-garage/yas-payment
    tag: latest

  nameOverride: payment
  fullnameOverride: payment
  databaseName: payment
  ingress:
    enabled: true
    host: api.yas.local.com
    path: /payment
